apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-consumer-scaler
  namespace: dev
spec:
  scaleTargetRef:
    name: keda-kafka-consumer
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 30
  cooldownPeriod: 300
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: >
        b-1.kafka.gk6ci4.c20.kafka.us-east-1.amazonaws.com:9096, b-1.kafka.gk6ci4.c20.kafka.us-east-1.amazonaws.com:9096
      consumerGroup: python-consumer-group
      topic: settlement-remuneration-unit-kafka-homolog
      lagThreshold: "1"
      offsetResetPolicy: latest
      sasl: plaintext
    authenticationRef:
      name: kafka-trigger-auth
