---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: policy-require-resource-limits
  annotations:
    policies.kyverno.io/title: Require Resource Limits and Requests
    policies.kyverno.io/category: Best Practices, Reliability
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Resource limits/requests previnem resource starvation e garantem scheduling previsível.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: check-resources
    match:
      any:
      - resources:
          kinds:
          - Pod
          - Deployment
          - StatefulSet
          - DaemonSet
    validate:
      message: "Containers devem ter resource requests (cpu, memory) e limits (cpu, memory)."
      pattern:
        spec:
          =(template):
            spec:
              containers:
              - resources:
                  requests:
                    memory: "?*"
                    cpu: "?*"
                  limits:
                    memory: "?*"
                    cpu: "?*"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: policy-require-probes
  annotations:
    policies.kyverno.io/title: Require Liveness and Readiness Probes
    policies.kyverno.io/category: Best Practices, Reliability
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Health checks (probes) são essenciais para detecção de falhas e self-healing automático.
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: check-liveness-readiness
    match:
      any:
      - resources:
          kinds:
          - Deployment
          - StatefulSet
          - DaemonSet
    validate:
      message: "Containers devem ter livenessProbe e readinessProbe configuradas."
      pattern:
        spec:
          template:
            spec:
              containers:
              - livenessProbe:
                  "?*": "?*"
                readinessProbe:
                  "?*": "?*"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: policy-require-pod-disruption-budget
  annotations:
    policies.kyverno.io/title: Require PodDisruptionBudget
    policies.kyverno.io/category: Reliability
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Deployment
    policies.kyverno.io/description: >-
      PodDisruptionBudget garante disponibilidade durante manutenções e atualizações do cluster.
spec:
  validationFailureAction: Audit
  background: false
  rules:
  - name: check-pdb-exists
    match:
      any:
      - resources:
          kinds:
          - Deployment
    preconditions:
      all:
      - key: "{{ request.object.spec.replicas }}"
        operator: GreaterThan
        value: 1
    validate:
      message: "Deployments com replicas > 1 devem ter um PodDisruptionBudget associado."
      deny: {}
