---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: policy-secret-classification
  annotations:
    policies.kyverno.io/title: Require Secret Classification Labels
    policies.kyverno.io/category: Security, Compliance
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      Secrets devem ter labels de classificação de dados para governança e auditoria (confidentiality: public|internal|confidential|restricted).
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: check-classification-label
    match:
      any:
      - resources:
          kinds:
          - Secret
    validate:
      message: >-
        Secret deve ter label 'confidentiality' com valor: public, internal, confidential, ou restricted.
      pattern:
        metadata:
          labels:
            confidentiality: "public | internal | confidential | restricted"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: policy-restrict-secret-role-binding
  annotations:
    policies.kyverno.io/title: Restrict Secret Access
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: RoleBinding
    policies.kyverno.io/description: >-
      Previne RoleBindings que concedem acesso amplo a secrets. Apenas ServiceAccounts específicas devem acessar secrets.
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: restrict-secret-access
    match:
      any:
      - resources:
          kinds:
          - RoleBinding
          - ClusterRoleBinding
    validate:
      message: "RoleBindings não devem conceder permissões wildcard (*) para secrets."
      deny:
        conditions:
          any:
          - key: "{{ request.object.roleRef.name }}"
            operator: Equals
            value: "cluster-admin"
